Add checks to allow logging only specific datatypes
salemove/lenjador pull request #46
Opened 2023-12-11 14:39 UTC by HallikiM

Also adding tests

---
Currently, it allows logging of objects and the whitelisting does not apply to the fields of that object.

This change adds data type checks and allows logging of only specific types so that data that is not whitelisted or that is blacklisted does not go through. This means it will be either masked or pruned.

MSG-709

2023-12-11 14:53 UTC, kmteras commented
You linked your team's caretaker journal. Could you also link the incident ticket (IN-299) or create an internal ticket for this problem for tracking fixes as well?

2023-12-11 18:28 UTC, indrekj commented
Tests please as well

2023-12-11 19:35 UTC, HallikiM commented
> You linked your team's caretaker journal. Could you also link the incident ticket (IN-299) or create an internal ticket for this problem for tracking fixes as well?

linked the incident ticket

2023-12-13 07:30 UTC, kmteras requested changes
Changes look fine but please add the tests

2023-12-13 14:30 UTC, kmteras approved these changes

2023-12-13 14:30 UTC, kmteras commented on spec/lenjador/preprocessors/whitelist_spec.rb
> +  end
Random fields, I know, but could name them something nicer 😄

2023-12-13 14:41 UTC, indrekj commented on spec/lenjador/preprocessors/whitelist_spec.rb
> +class Test
This is a bad name to have globally defined. You don't need a global class, you can do:
```
let(:data) do
  Class.new do
    attr_accessor :some_attribute
    #...
  end.new
end
```
I personally would use an open struct instead:
```
let(:data) { OpenStruct.new(:name => "Rowdy", :owner => "John Smith") }
```

2023-12-13 14:46 UTC, indrekj commented on lib/lenjador/preprocessors/strategies/prune.rb
> +          when String, Numeric, Symbol, Date, Time, TrueClass, FalseClass, NilClass
`Date` is not loaded by default.

```
 ~ irb
irb(main):001:0> Date
Traceback (most recent call last):
        4: from /home/indrek/.asdf/installs/ruby/2.7.8/bin/irb:23:in `<main>'
        3: from /home/indrek/.asdf/installs/ruby/2.7.8/bin/irb:23:in `load'
        2: from /home/indrek/.asdf/installs/ruby/2.7.8/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NameError (uninitialized constant Date)
```
And if it's loaded, then there's also `DateTime`.

2023-12-13 17:21 UTC, HallikiM commented on lib/lenjador/preprocessors/strategies/prune.rb
> +          when String, Numeric, Symbol, Date, Time, TrueClass, FalseClass, NilClass
Added tests for this as well. DateTime is subclass of Date.

2023-12-13 18:46 UTC, indrekj commented
@HallikiM https://github.com/salemove/lenjador/pull/46/files#r1425454770

2023-12-13 20:18 UTC, indrekj approved these changes

2023-12-13 20:19 UTC, merged